include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build_container
  - make_multiarch

variables:
    DEPLOYMENT_VERSION: '0.14'

.build-container:
  stage: build_container
  script:
    - cd santis
    - build_new_container
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GITLAB_RUNNER_VERSION: "v16.7.0"
    USER_ID: '25014'
    GROUP_ID: '31774'
    DOCKERFILE: Dockerfile.container_build
    PERSIST_IMAGE_NAME: $CI_REGISTRY_IMAGE/cicd-ext-$CI_COMMIT_REF_SLUG-gitlab-runner:$DEPLOYMENT_VERSION-${ARCH}
    DOCKER_BUILD_ARGS: '["GITLAB_RUNNER_VERSION=$GITLAB_RUNNER_VERSION", "USER_ID=$USER_ID", "GROUP_ID=$GROUP_ID"]'
build aarch64:
  extends: [.container-builder-cscs-gh200, .build-container]
build x86_64:
  extends: [.container-builder-cscs-zen2, .build-container]

make multiarch:
  extends: .make-multiarch-image
  stage: make_multiarch
  variables:
    PERSIST_IMAGE_NAME: $CI_REGISTRY_IMAGE/cicd-ext-$CI_COMMIT_REF_SLUG-gitlab-runner:$DEPLOYMENT_VERSION
    PERSIST_IMAGE_NAME_AARCH64: $CI_REGISTRY_IMAGE/cicd-ext-$CI_COMMIT_REF_SLUG-gitlab-runner:$DEPLOYMENT_VERSION-aarch64
    PERSIST_IMAGE_NAME_X86_64: $CI_REGISTRY_IMAGE/cicd-ext-$CI_COMMIT_REF_SLUG-gitlab-runner:$DEPLOYMENT_VERSION-x86_64

